name: CubeDisplay
main: org.myftp.p_productions.spigot.CubeDisplay.CubeDisplay
version: __build.number__
softdepend: [WorldGuard, WorldEdit]
commands:
  cube:
    description: Display a cube
    usage: /<command> <<x1> <y1> <z1> <x2> <y2> <z2> | <region>> [name]
  decube:
    description: Deletes a cube
    usage: /<command> <name>
  cubes:
    description: Lists all cubes
    usage: /<command>
    aliases: cubelist
    
permissions:
  cubedisplay.*:
    description: Gives access to all Cube Display commands
    children:
      cubedisplay.cube: true
      cubedisplay.decube: true
      cubedisplay.cubes: true
      cubedisplay.debugMsg: true
    default: op
  cubedisplay.cube:
    description: Allows to display a cube 
    default: true
  cubedisplay.decube:
    description: Allows to delete a cube 
    default: true
  cubedisplay.cubes:
    description: Allows to list all cubes 
    default: true
  cubedisplay.debugMsg:
    description: Allows to recieve debug messages
    default: op